alter table trading_signal_daily
  add column if not exists historical_edge_fingerprint text,
  add column if not exists historical_edge_direction text default 'neutral',
  add column if not exists historical_edge_score numeric,
  add column if not exists markov_state text,
  add column if not exists markov_bull_probability numeric,
  add column if not exists markov_sideways_probability numeric,
  add column if not exists markov_bear_probability numeric,
  add column if not exists markov_edge numeric,
  add column if not exists markov_stickiness numeric,
  add column if not exists markov_sample_size integer default 0,
  add column if not exists forward_5d_avg_return numeric,
  add column if not exists forward_5d_win_rate numeric,
  add column if not exists forward_20d_avg_return numeric,
  add column if not exists forward_20d_win_rate numeric,
  add column if not exists forward_sample_size integer default 0,
  add column if not exists state_duration_days integer default 0,
  add column if not exists state_duration_percentile numeric,
  add column if not exists state_exhaustion_risk boolean default false;
