create table if not exists implied_volatility_ratio_signals_daily (
  date date not null,
  asset_key text not null,
  asset_name text not null,
  asset_type text,
  source_symbol text not null,
  source_status text not null default 'active',
  close numeric,
  implied_volatility numeric,
  realised_volatility_30d numeric,
  realised_volatility_30d_5d_change numeric,
  realised_volatility_30d_rising_sharply boolean,
  ivol_rvol_ratio numeric,
  ivol_rvol_ratio_z_1y numeric,
  ivol_rvol_ratio_z_1w_ago numeric,
  ivol_rvol_ratio_z_1w_change numeric,
  ivol_rvol_ratio_z_1y_min numeric,
  ivol_rvol_ratio_z_1y_max numeric,
  rvol_20d numeric,
  rvol_bucket text,
  close_above_ma20 boolean,
  close_above_ma50 boolean,
  close_above_ma200 boolean,
  ma20_slope_20d numeric,
  ma50_slope_20d numeric,
  trend_regime text,
  range_position_20d numeric,
  range_bucket text,
  ivol_rvol_level text,
  signal text not null,
  action text not null,
  opportunity_score numeric,
  ivol_rvol_rank integer,
  ivol_rvol_percentile numeric,
  row_values jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (date, asset_key)
);

create index if not exists implied_volatility_ratio_signals_daily_date_rank_idx
  on implied_volatility_ratio_signals_daily (date, ivol_rvol_rank);
