import test from 'node:test';
import assert from 'node:assert/strict';
import { buildPositionSignalRowsFromSources } from '../lib/utils/position-signals.js';

test('buildPositionSignalRowsFromSources requires a 2-day 4-flag hard-risk cluster before going fully to cash', () => {
  const positionFactRows = [
    {
      date: '2026-03-31',
      sp500_trend_regime: 'above_200dma',
      vix_regime: 'calm',
      credit_regime: 'calm',
      yield_curve_regime: 'normal',
      fed_policy_trend: 'stable',
      labor_trend: 'stable',
      inflation_trend: 'cooling',
      sentiment_trend: 'improving',
    },
    {
      date: '2026-04-01',
      sp500_trend_regime: 'above_200dma',
      vix_regime: 'calm',
      credit_regime: 'calm',
      yield_curve_regime: 'normal',
      fed_policy_trend: 'stable',
      labor_trend: 'stable',
      inflation_trend: 'heating_up',
      sentiment_trend: 'stable',
    },
    {
      date: '2026-04-02',
      sp500_trend_regime: 'above_200dma',
      vix_regime: 'elevated',
      credit_regime: 'elevated',
      yield_curve_regime: 'flat',
      fed_policy_trend: 'tightening',
      labor_trend: 'stable',
      inflation_trend: 'stable',
      sentiment_trend: 'stable',
    },
    {
      date: '2026-04-03',
      sp500_trend_regime: 'below_200dma',
      vix_regime: 'stress',
      credit_regime: 'stress',
      yield_curve_regime: 'inverted',
      fed_policy_trend: 'tightening',
      labor_trend: 'deteriorating',
      inflation_trend: 'heating_up',
      sentiment_trend: 'deteriorating',
    },
    {
      date: '2026-04-04',
      sp500_trend_regime: 'below_200dma',
      vix_regime: 'stress',
      credit_regime: 'stress',
      yield_curve_regime: 'inverted',
      fed_policy_trend: 'tightening',
      labor_trend: 'deteriorating',
      inflation_trend: 'heating_up',
      sentiment_trend: 'deteriorating',
    },
  ];
  const marketSignalRows = [
    {
      date: '2026-03-31',
      market_regime_score: 4,
      signal: 'risk_on',
    },
    {
      date: '2026-04-01',
      market_regime_score: 4,
      signal: 'risk_on',
    },
    {
      date: '2026-04-02',
      market_regime_score: 0,
      signal: 'warning',
    },
    {
      date: '2026-04-03',
      market_regime_score: -3,
      signal: 'risk_off',
    },
    {
      date: '2026-04-04',
      market_regime_score: -3,
      signal: 'risk_off',
    },
  ];

  const rows = buildPositionSignalRowsFromSources({
    positionFactRows,
    marketSignalRows,
  });

  assert.deepEqual(rows, [
    {
      date: '2026-03-31',
      signal: 'risk_on',
      decision: 'FULLT INVESTERAD (100%)',
      target_equity_weight_pct: 100,
      target_cash_weight_pct: 0,
      raw_signal: 'risk_on',
      raw_decision: 'FULLT INVESTERAD (100%)',
      raw_target_equity_weight_pct: 100,
      raw_target_cash_weight_pct: 0,
      market_signal: 'risk_on',
      market_regime_score: 4,
      caution_count: 0,
      hard_risk_off_count: 0,
      reason_summary: 'supportive_macro_and_breadth',
      persistence_direction: 'none',
      persistence_streak_days: 0,
      persistence_required_days: 0,
    },
    {
      date: '2026-04-01',
      signal: 'risk_on',
      decision: 'FULLT INVESTERAD (100%)',
      target_equity_weight_pct: 100,
      target_cash_weight_pct: 0,
      raw_signal: 'risk_on',
      raw_decision: 'FULLT INVESTERAD (100%)',
      raw_target_equity_weight_pct: 100,
      raw_target_cash_weight_pct: 0,
      market_signal: 'risk_on',
      market_regime_score: 4,
      caution_count: 0,
      hard_risk_off_count: 0,
      reason_summary: 'supportive_macro_and_breadth',
      persistence_direction: 'none',
      persistence_streak_days: 0,
      persistence_required_days: 0,
    },
    {
      date: '2026-04-02',
      signal: 'risk_on',
      decision: 'FULLT INVESTERAD (100%)',
      target_equity_weight_pct: 100,
      target_cash_weight_pct: 0,
      raw_signal: 'risk_caution',
      raw_decision: 'DELVIS INVESTERAD (50%)',
      raw_target_equity_weight_pct: 50,
      raw_target_cash_weight_pct: 50,
      market_signal: 'warning',
      market_regime_score: 0,
      caution_count: 5,
      hard_risk_off_count: 0,
      reason_summary: 'persistence_hold_for_reduction',
      persistence_direction: 'reduction',
      persistence_streak_days: 1,
      persistence_required_days: 3,
    },
    {
      date: '2026-04-03',
      signal: 'risk_on',
      decision: 'FULLT INVESTERAD (100%)',
      target_equity_weight_pct: 100,
      target_cash_weight_pct: 0,
      raw_signal: 'risk_caution',
      raw_decision: 'DELVIS INVESTERAD (50%)',
      raw_target_equity_weight_pct: 50,
      raw_target_cash_weight_pct: 50,
      market_signal: 'risk_off',
      market_regime_score: -3,
      caution_count: 5,
      hard_risk_off_count: 4,
      reason_summary: 'persistence_hold_for_reduction',
      persistence_direction: 'reduction',
      persistence_streak_days: 2,
      persistence_required_days: 3,
    },
    {
      date: '2026-04-04',
      signal: 'risk_off',
      decision: 'GÅ TILL CASH',
      target_equity_weight_pct: 0,
      target_cash_weight_pct: 100,
      raw_signal: 'risk_off',
      raw_decision: 'GÅ TILL CASH',
      raw_target_equity_weight_pct: 0,
      raw_target_cash_weight_pct: 100,
      market_signal: 'risk_off',
      market_regime_score: -3,
      caution_count: 5,
      hard_risk_off_count: 4,
      reason_summary: 'hard_risk_cluster_cash',
      persistence_direction: 'none',
      persistence_streak_days: 0,
      persistence_required_days: 0,
    },
  ]);
});

test('buildPositionSignalRowsFromSources scales down after sustained 3+ hard flags and waits 5 days before reopening', () => {
  const positionFactRows = [
    { date: '2026-05-01', sp500_trend_regime: 'above_200dma', vix_regime: 'calm', credit_regime: 'calm', yield_curve_regime: 'normal', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-02', sp500_trend_regime: 'below_200dma', vix_regime: 'stress', credit_regime: 'stress', yield_curve_regime: 'inverted', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-03', sp500_trend_regime: 'below_200dma', vix_regime: 'stress', credit_regime: 'stress', yield_curve_regime: 'inverted', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-04', sp500_trend_regime: 'below_200dma', vix_regime: 'stress', credit_regime: 'stress', yield_curve_regime: 'inverted', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-05', sp500_trend_regime: 'below_200dma', vix_regime: 'stress', credit_regime: 'stress', yield_curve_regime: 'inverted', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-06', sp500_trend_regime: 'below_200dma', vix_regime: 'stress', credit_regime: 'stress', yield_curve_regime: 'inverted', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-07', sp500_trend_regime: 'above_200dma', vix_regime: 'calm', credit_regime: 'calm', yield_curve_regime: 'normal', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-08', sp500_trend_regime: 'above_200dma', vix_regime: 'calm', credit_regime: 'calm', yield_curve_regime: 'normal', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-09', sp500_trend_regime: 'above_200dma', vix_regime: 'calm', credit_regime: 'calm', yield_curve_regime: 'normal', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-10', sp500_trend_regime: 'above_200dma', vix_regime: 'calm', credit_regime: 'calm', yield_curve_regime: 'normal', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
    { date: '2026-05-11', sp500_trend_regime: 'above_200dma', vix_regime: 'calm', credit_regime: 'calm', yield_curve_regime: 'normal', fed_policy_trend: 'stable', labor_trend: 'stable', inflation_trend: 'cooling', sentiment_trend: 'stable' },
  ];
  const marketSignalRows = [
    { date: '2026-05-01', market_regime_score: 4, signal: 'risk_on' },
    { date: '2026-05-02', market_regime_score: 1, signal: 'warning' },
    { date: '2026-05-03', market_regime_score: 1, signal: 'warning' },
    { date: '2026-05-04', market_regime_score: 1, signal: 'warning' },
    { date: '2026-05-05', market_regime_score: 1, signal: 'warning' },
    { date: '2026-05-06', market_regime_score: 1, signal: 'warning' },
    { date: '2026-05-07', market_regime_score: 4, signal: 'risk_on' },
    { date: '2026-05-08', market_regime_score: 4, signal: 'risk_on' },
    { date: '2026-05-09', market_regime_score: 4, signal: 'risk_on' },
    { date: '2026-05-10', market_regime_score: 4, signal: 'risk_on' },
    { date: '2026-05-11', market_regime_score: 4, signal: 'risk_on' },
  ];

  const rows = buildPositionSignalRowsFromSources({
    positionFactRows,
    marketSignalRows,
  });

  assert.deepEqual(
    rows.map((row) => ({
      date: row.date,
      hard_risk_off_count: row.hard_risk_off_count,
      raw_target_equity_weight_pct: row.raw_target_equity_weight_pct,
      target_equity_weight_pct: row.target_equity_weight_pct,
      reason_summary: row.reason_summary,
      persistence_direction: row.persistence_direction,
      persistence_streak_days: row.persistence_streak_days,
      persistence_required_days: row.persistence_required_days,
    })),
    [
      { date: '2026-05-01', hard_risk_off_count: 0, raw_target_equity_weight_pct: 100, target_equity_weight_pct: 100, reason_summary: 'supportive_macro_and_breadth', persistence_direction: 'none', persistence_streak_days: 0, persistence_required_days: 0 },
      { date: '2026-05-02', hard_risk_off_count: 3, raw_target_equity_weight_pct: 75, target_equity_weight_pct: 100, reason_summary: 'persistence_hold_for_reduction', persistence_direction: 'reduction', persistence_streak_days: 1, persistence_required_days: 3 },
      { date: '2026-05-03', hard_risk_off_count: 3, raw_target_equity_weight_pct: 75, target_equity_weight_pct: 100, reason_summary: 'persistence_hold_for_reduction', persistence_direction: 'reduction', persistence_streak_days: 2, persistence_required_days: 3 },
      { date: '2026-05-04', hard_risk_off_count: 3, raw_target_equity_weight_pct: 50, target_equity_weight_pct: 50, reason_summary: 'hard_risk_cluster_3d', persistence_direction: 'none', persistence_streak_days: 0, persistence_required_days: 0 },
      { date: '2026-05-05', hard_risk_off_count: 3, raw_target_equity_weight_pct: 50, target_equity_weight_pct: 50, reason_summary: 'hard_risk_cluster_3d', persistence_direction: 'none', persistence_streak_days: 0, persistence_required_days: 0 },
      { date: '2026-05-06', hard_risk_off_count: 3, raw_target_equity_weight_pct: 25, target_equity_weight_pct: 25, reason_summary: 'hard_risk_cluster_5d', persistence_direction: 'none', persistence_streak_days: 0, persistence_required_days: 0 },
      { date: '2026-05-07', hard_risk_off_count: 0, raw_target_equity_weight_pct: 100, target_equity_weight_pct: 25, reason_summary: 'persistence_hold_for_increase', persistence_direction: 'increase', persistence_streak_days: 1, persistence_required_days: 5 },
      { date: '2026-05-08', hard_risk_off_count: 0, raw_target_equity_weight_pct: 100, target_equity_weight_pct: 25, reason_summary: 'persistence_hold_for_increase', persistence_direction: 'increase', persistence_streak_days: 2, persistence_required_days: 5 },
      { date: '2026-05-09', hard_risk_off_count: 0, raw_target_equity_weight_pct: 100, target_equity_weight_pct: 25, reason_summary: 'persistence_hold_for_increase', persistence_direction: 'increase', persistence_streak_days: 3, persistence_required_days: 5 },
      { date: '2026-05-10', hard_risk_off_count: 0, raw_target_equity_weight_pct: 100, target_equity_weight_pct: 25, reason_summary: 'persistence_hold_for_increase', persistence_direction: 'increase', persistence_streak_days: 4, persistence_required_days: 5 },
      { date: '2026-05-11', hard_risk_off_count: 0, raw_target_equity_weight_pct: 100, target_equity_weight_pct: 100, reason_summary: 'supportive_macro_and_breadth', persistence_direction: 'none', persistence_streak_days: 0, persistence_required_days: 0 },
    ]
  );
});
