import test from 'node:test';
import assert from 'node:assert/strict';
import { buildSectorBreadthRows } from '../lib/utils/sector-breadth.js';

test('buildSectorBreadthRows aggregates breadth counts per sector and date', () => {
  const rows = [
    {
      ticker: 'AAPL',
      sector: 'Information Technology',
      date: '2026-01-02',
      indicator_price: 110,
      daily_return_pct: 2,
      sma20: 100,
      sma50: 120,
      sma200: 90,
      pct_from_52w_high: 0,
      pct_from_52w_low: 80,
    },
    {
      ticker: 'MSFT',
      sector: 'Information Technology',
      date: '2026-01-02',
      indicator_price: 90,
      daily_return_pct: -1,
      sma20: 100,
      sma50: 80,
      sma200: 85,
      pct_from_52w_high: -10,
      pct_from_52w_low: 0,
    },
    {
      ticker: 'XOM',
      sector: 'Energy',
      date: '2026-01-02',
      indicator_price: 50,
      daily_return_pct: 0,
      sma20: 45,
      sma50: 55,
      sma200: null,
      pct_from_52w_high: -5,
      pct_from_52w_low: 12,
    },
    {
      ticker: 'MISSING',
      sector: null,
      date: '2026-01-02',
      indicator_price: 50,
      daily_return_pct: 1,
      sma20: 45,
      sma50: 40,
      sma200: 35,
      pct_from_52w_high: -5,
      pct_from_52w_low: 12,
    },
  ];

  assert.deepEqual(buildSectorBreadthRows(rows, 0.5), [
    {
      date: '2026-01-02',
      sector: 'Energy',
      active_ticker_count: 1,
      advancers: 0,
      decliners: 0,
      unchanged: 1,
      valid_sma20_count: 1,
      above_sma20_count: 1,
      valid_sma50_count: 1,
      above_sma50_count: 0,
      valid_sma200_count: 0,
      above_sma200_count: 0,
      valid_52w_count: 1,
      new_highs_52w: 0,
      new_lows_52w: 0,
      pct_above_sma20: 100,
      pct_above_sma50: 0,
      pct_above_sma200: null,
      is_valid_signal_date: false,
    },
    {
      date: '2026-01-02',
      sector: 'Information Technology',
      active_ticker_count: 2,
      advancers: 1,
      decliners: 1,
      unchanged: 0,
      valid_sma20_count: 2,
      above_sma20_count: 1,
      valid_sma50_count: 2,
      above_sma50_count: 1,
      valid_sma200_count: 2,
      above_sma200_count: 2,
      valid_52w_count: 2,
      new_highs_52w: 1,
      new_lows_52w: 1,
      pct_above_sma20: 50,
      pct_above_sma50: 50,
      pct_above_sma200: 100,
      is_valid_signal_date: true,
    },
  ]);
});
